### ISSUE TITLE
The code available time

### ISSUE THREAD

**Issue by jackhu-bme** [shash29-dev/GraphFill#1]
Congratulations on being accepted to WACV2024!
I really love this work, as a researcher working on medical image inpainting. It's the best work I could see about employing graph onto the task of image inpainting/generation. 
For me, I'm planning to use graphs to dig out the correlation of different anatomical structures of human body, and employ the correlation represented by graphs to inpaint medical images. This approach will greatly improve the explananbility of medical image inpainting. So your work  is of great importance for me, I would like to cite your paper and show acknowledgement if my work can be finished.
I'm wondering when the code will be available. This would beneifit me a lot and accelerate my work greatly. Thanks a lot if the time can be told. 
Thank you again for your dedication to the community of image generation/inpainting.

**Comment by shash29-dev** [comment]
Thanks for your interest in GraphFill. We have updated the repository with code.

**Comment by jackhu-bme** [comment]
That's so amazing! I'll deep dive into the code and employ it for my work, thank you for your hard work!
